### PR TITLE
Update version, add images

### PR DESCRIPTION
**Pull request by CCYChongyanChen**
1. update version number starting from 0 instead of 1. 
2. add two mages

### CODE REVIEW

**Comment by jameshowison** [comment]
Lots to like here. Great start.  Pictures and approach are good.

I'd like to keep the two exercises separate, though. So think of the two different days that we did.

1. Sharing improvements, patents, copyright.  (no need for conflicts, version numbers). https://github.com/howisonlab/open_source_software_course/blob/master/docs/paper_plane_analogy.md
2. Introducing version control and git.  https://github.com/howisonlab/open_source_software_course/blob/master/docs/paper_planes/paper_planes_git.Rmd

You can refactor these into the same docs/paper_planes folder.  Call the first one paper_plane_sharing.md and the second one paper_plane_git.md  You can change the second one from Rmd to just straight md

**Comment by jameshowison** [comment]
Useful changes, making progress.  Could you hit the "Allow edits from maintainers." option, so that I can push changes to the branch in your fork?  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Two things:  can you write commit messages that explain the changes more clearly?  Also updating the conversation in the Pull Request is useful as well.

The figures are close but they don't match what we did in class.  There we had three tables and they are important because they are the "working space" of Improver 1 and Improver 2. The table in the middle is the repository.

Can you also explore how to include code for the figures?  It's always a pain, frankly.  I'd love some ideas about how to create figures from inside the Rmarkdown, so that one doesn't have to edit a graphics file, export a gif etc as one is making changes.

**Comment by CCYChongyanChen** [comment]
- Sure. I have checked the "allow edits from maintainer" button, let me know if it works.
- I will explain the changes more detailed in the future. 
- Does the following look correct? 
image
The instructions in the tutorial didn't mention improver 2 though.
image
-  Sure, I will explore how to create figures with Rmarkdown. Could you give me more context about this? I am not sure what "includes code for the figures" mean. 


```{r}
{r, fig.width = 4}
# Bigger fig.width
ggplot(cars, aes(speed, dist)) + geom_point()
```

https://stackoverflow.com/questions/25166624/insert-picture-table-in-r-markdown

**Comment by jameshowison** [comment]
Yes, this looks good.  You are right, we had originator and improver1 not
improver 2.

The code for the figures stuff is asking a lot, perhaps too much.  Notice
how easy it is for us to edit the file and store those edits in github,
then regenerate the page.  But with the figures we have to edit a graphics
file, and then re-export every figure.  If figures could be generated from
code then that wouldn't happen.

Yes, graphs like ggplot do that (but seems hard to imagine drawing these
figures using ggplot, maybe not impossible?)  Other code to drawing
approaches include things like this:
https://support.typora.io/Draw-Diagrams-With-Markdown/

So perhaps I'm not being realistic, just wondered if there was an option,
sometimes new eyes help solve those things :)

--J

**Comment by jameshowison** [comment]
I added an introduction to the page, and I can push to this PR now, so that's cool.

**Comment by CCYChongyanChen** [comment]
I added the draft tutorial for the first git exercise, including ls,cd,mkdir; git add, git commit, git log

**Comment by CCYChongyanChen** [comment]
Updated figures in the paper_planes_git.md (1table->3 tables)

**Comment by jameshowison** [comment]
Looks good.  Images weren't showing up in the html (for me, pandoc and rstudio). Not sure what the issue was, it is either the location of the images or that you used the `\` character in the paths rather than `/`.

Ah, looking at the git tutorial instructions, it was definitely the reversed paths that were giving trouble :)

Ok, merged and closed this!

**Pull request merged**
